// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_get_mail_ from "./routes/api/get/[mail].tsx";
import * as $api_post_mail_ from "./routes/api/post/[mail].tsx";
import * as $index from "./routes/index.tsx";
import * as $AddMailForm from "./islands/AddMailForm.tsx";
import * as $Form from "./islands/Form.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/get/[mail].tsx": $api_get_mail_,
    "./routes/api/post/[mail].tsx": $api_post_mail_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AddMailForm.tsx": $AddMailForm,
    "./islands/Form.tsx": $Form,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
